#!/usr/bin/env python
# -*- coding: utf-8 -*-

import urllib.request, sys
import os
from xml.dom import minidom
from pprint import pprint

def getNodeText(node):

    nodelist = node.childNodes
    result = []
    for node in nodelist:
        if node.nodeType == node.TEXT_NODE:
            result.append(node.data)
    return ''.join(result)

def getFilname(file):
	#http://stackoverflow.com/a/678266
	return os.path.splitext(os.path.basename(file))[0]

def main():
	if len(sys.argv) >= 2:
		name = sys.argv[1]
	else:
		sys.exit(0)

xmldoc = minidom.parse(sys.argv[1])

filename = getFilname(sys.argv[1])

langlist = xmldoc.getElementsByTagName('div')

style = '[V4+ Styles]\n'
style += 'Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding\n'
style += 'Style: Main,Open Sans Semibold,36,&H00FFFFFF,&H000000FF,&H00020713,&H00000000,-1,0,0,0,100,100,0,0,1,1.7,0,2,0,0,28,1\n'

langlist = xmldoc.getElementsByTagName('div')

for lang in langlist:
	#print(lang.attributes['xml:lang'].value)
	f = open(filename + ' - ' + lang.attributes['xml:lang'].value + '.ass', 'w')

	header = '[Script Info]\n'
	header += '; Script generated by Aegisub 3.2.2\n'
	header += '; http://www.aegisub.org/\n'
	header += 'Title: ' + filename + ' - ' + lang.attributes['xml:lang'].value + '.ass' + '\n'
	header += 'ScriptType: v4.00+\n'
	header += 'WrapStyle: 0\n'
	header += 'PlayResX: 848\n'
	header += 'PlayResY: 480\n'

	f.write(header)
	f.write('\n')
	f.write(style)
	f.write('\n')

	f.write('[Events]\n')
	f.write('Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\n')
	linelist = lang.getElementsByTagName('p')
	for line in linelist:
		line = 'Dialogue: 0,' + str(line.attributes['begin'].value)[1:-1] + ','+ str(line.attributes['end'].value)[1:-1] + ',Main,,0,0,0,,' + getNodeText(line).replace("\n", "").replace("\t", "\\N")[2:-2] + '\n'
		f.write(line)
		#print(str(line))
	f.close()

#style = 
#[Script Info]
#Title: Français (France)
#ScriptType: v4.00+
#WrapStyle: 0
#PlayResX: 640
#PlayResY: 360
#ScaledBorderAndShadow: yes

if __name__ == '__main__':
	main()
